apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-flash-cards-cluster
  region: ca-central-1

managedNodeGroups:
  - name: worker-nodes
    instanceType: t2.micro
    minSize: 2
    maxSize: 4
    desiredCapacity: 3

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]