version: '2'
services:
  redis-svc:
    container_name: redis-svc
    image: redis
    expose:
      - 6379
  backend-svc:
    container_name: backend-svc
    build: 
      context: ./backend
    image: ai-flash-cards/backend
    expose:
      - 8000
    volumes:
      - ~/.aws/:/root/.aws/:ro
    depends_on:
      - redis-svc
  nginx-svc:
    container_name: nginx-svc
    build: 
      context: ./reverse_proxy
    image: ai-flash-cards/reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - backend-svc
  frontend-svc:
    container_name: frontend-svc
    build:
      context: ./frontend
    image: ai-flash-cards/todo-frontend
    ports:
      - 3000:80
    depends_on:
      - nginx-svc