apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cherisecodes/ai-flash-cards-backend:latest
          ports:
            - name: http
              containerPort: 8000
          env:
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: aws-default-region
          - name: BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: bucket-name
          - name: CLOUDFRONT_URL
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: cloudfront-url
          readinessProbe:
            httpGet:
              path: /service/readyz
              port: 8000
            periodSeconds: 5
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /service/livez
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
          volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
            readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: api-secret