apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.backend.secret.name }}
  labels:
    {{- include "ai-flash-cards.labels" . | nindent 4 }}
type: {{ .Values.backend.secret.type }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backend.secret.data.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.secret.data.awsSecretAccessKey }}
  AWS_SESSION_TOKEN: {{ .Values.backend.secret.data.awsSessionToken }}
  OPENAI_API_KEY: {{ .Values.backend.secret.data.openaiApiKey }}