apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.backend.config.name }}
  labels:
    {{- include "ai-flash-cards.labels" . | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.backend.config.data.awsDefaultRegion }}
  BUCKET_NAME: {{ .Values.backend.config.data.bucketName }}
  CLOUDFRONT_URL: {{ .Values.backend.config.data.cloudfrontUrl }}
  NODE_ENV: {{ .Values.backend.config.data.nodeEnv }}
  APP_ENV: {{ .Values.backend.config.data.appEnv }}