apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-flash-cards.fullname" . }}-backend-deployment
  labels:
    {{- include "ai-flash-cards.labels" . | nindent 4 }}
    app: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-flash-cards.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ai-flash-cards.labels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.registry }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.backend.config.name }}
          - secretRef:
              name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.backend.secret.name }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
