apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.frontend.config.name }}
  labels:
    {{- include "ai-flash-cards.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.frontend.config.data.nodeEnv }}