apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-flash-cards.fullname" . }}-{{ .Values.frontend.service.name }}
  labels:
    {{- include "ai-flash-cards.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    {{- include "ai-flash-cards.selectorLabels" . | nindent 4 }}
    app: frontend