apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    service: nginx-reverseproxy
spec:
  selector:
    service: nginx-reverseproxy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer