apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.localdev.me
    secretName: nginx-ingress-cert
  rules:
  - host: demo.localdev.me
    http:
      paths:
      - path: /?(.*) 
        pathType: ImplementationSpecific 
        backend:
          service:
            name: frontend-service
            port:
              number: 80 
      - path: /backend/?(.*) 
        pathType: ImplementationSpecific 
        backend:
          service:
            name: backend-service
            port:
              number: 8000 
