{{- if .Values.frontend.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-svc
  minReplicas: {{ .Values.frontend.hpa.replicaCount }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
  {{- if .Values.frontend.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.hpa.cpu }}
  {{- end }}
{{- end }}
  