apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
  labels:
    service: frontend
spec:
  {{- if not .Values.frontend.hpa.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - name: frontend-svc
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            initialDelaySeconds: 5
            periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            initialDelaySeconds: 5
            periodSeconds: 5