apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-svc
  labels:
    service: reverse-proxy
spec:
  {{- if not .Values.nginx.hpa.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: reverse-proxy
  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy-svc
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            initialDelaySeconds: 5
            periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            initialDelaySeconds: 5
            periodSeconds: 5