AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Cloudfront resources for serving static resources (CDN)

Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig: 
        Description: "Allow users to retrieve images from the OpenAI S3 bucket"
        Name: OpenAIS3OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        DefaultRootObject: index.html
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          SmoothStreaming: false
          TargetOriginId: OpenAIS3
          ViewerProtocolPolicy: allow-all
        Comment: "Distribute OpenAI S3 image objects"
        Enabled: true
        PriceClass: PriceClass_100
        Origins:
          - Id: OpenAIS3
            S3OriginConfig: 
              OriginAccessIdentity: ''
            DomainName: openai-dalle-s3-40d44616.s3.ca-central-1.amazonaws.com
            OriginAccessControlId: E1I3UJ9TG0DQYP
      Tags:
        - Key: Purpose
          Value: Testing
