AWSTemplateFormatVersion: "2010-09-09"
Description: S3 resources to store data for GenAI flash card application

Parameters:
  BucketName:
    Type: String
    Description: Bucket to store DALLE images

Resources:
  OpenAIDalleSBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: 
              - "GET"
            AllowedOrigins: 
              - "*"
            Id: ShareImages
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
