AWSTemplateFormatVersion: "2010-09-09"
Description: ECR resources to store container images for GenAI flash card application
Resources:
  FrontendRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ai-flash-cards/frontend
  BackendRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ai-flash-cards/backend
  ReverseProxyRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ai-flash-cards/reverse-proxy
  LBCRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: eks/aws-load-balancer-controller
