apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-flash-cards
  region: ca-central-1

nodeGroups:
  - name: node-group
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    ssh:
      publicKeyName: EC2_KP_NAME

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator"]
    logRetentionInDays: 7

secretsEncryption:
  keyARN: arn:aws:kms:REGION:ACCOUNT_ID:key/SECRETS_KMS_ID
