# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend Node.js CI

on:
  push:
    branches: [ "backend" ]
    paths:
      - "src/**"
      - "__test__/**"
  pull_request:
    branches: [ "main", "pre-release" ]
    paths:
      - "src/**"
      - "__test__/**"
env:
  OPENAI_API_KEY: "sk-123abc"
  BUCKET_NAME: "bucket-name"
  CLOUDFRONT_URL: "cloudfront-url"
  AWS_PROFILE: "aws-profile"
defaults:
  run:
    working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases/
    steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - uses: actions/checkout@v3
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: bun run test
