# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Deployment to Docker and ECR

on:
  pull_request:
    branches: [ "main"]
    paths:
      - "frontend/src/**"
      - "backend/src/**"
env:
  AWS_REGION: ca-central-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_FRONTEND_REPOSITORY: dkr.ecr.ca-central-1.amazonaws.com/ai-flash-cards/frontend

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          build-args: APP_ENV=kubernetes.development
          push: true
          tags: cherisecodes/ai-flash-cards-frontend:latest
  build-push-ecr:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t "$ECR_REGISTRY/$AWS_ACCOUNT_ID.$ECR_FRONTEND_REPOSITORY:$IMAGE_TAG" --build-arg APP_ENV=kubernetes.production .
          docker push "$ECR_REGISTRY/$AWS_ACCOUNT_ID.$ECR_FRONTEND_REPOSITORY:$IMAGE_TAG"
          echo "image=$ECR_REGISTRY/$AWS_ACCOUNT_ID.$ECR_FRONTEND_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
