# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Continuous Deployment to Docker and ECR

on:
  push:
    branches: [ "main"]
    paths:
      - "frontend/src/**"
env:
  AWS_REGION: ca-central-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ai-flash-cards/frontend
  EKS_CLUSTER_NAME: ai-flash-cards

defaults:
 run:
  working-directory: ./frontend

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          build-args: APP_ENV=docker.test
          progress: plain
          no-cache: true
          target: test
          tags: cherisecodes/ai-flash-cards-frontend:latest
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          build-args: APP_ENV=kubernetes.development
          push: true
          tags: cherisecodes/ai-flash-cards-frontend:latest
  build-push-ecr-eks:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:latest" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" --build-arg APP_ENV=kubernetes.production .
          docker push --all-tags "$ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          CERT_ID: ${{ secrets.CERT_ID }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          cd ../helm/
          yq e -i '.frontend.image.registry = "$ECR_REGISTRY"' ai-flash-cards/eks-values.yaml
          yq e -i '.backend.image.registry = "$ECR_REGISTRY"' ai-flash-cards/eks-values.yaml
          yq e -i '.backend.image.tag = "$IMAGE_TAG"' ai-flash-cards/eks-values.yaml
          yq e -i '.ingress.hosts[0].host = "$DOMAIN_NAME"' ai-flash-cards/eks-values.yaml
          sed -i.bak "s|AWS_REGION|$AWS_REGION|g" ai-flash-cards/eks-values.yaml  
          sed -i.bak "s|AWS_ACCOUNT_ID|$AWS_ACCOUNT_ID|g" ai-flash-cards/eks-values.yaml 
          helm upgrade -i ai-flash-cards ./ai-flash-cards -f ./ai-flash-cards/eks-values.yaml -n ai-flash-cards --create-namespace
