# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend React CI

on:
  pull_request:
    branches: [ "main", "fullstack-release", "frontend-release" ]
    paths:
      - "frontend/**"

env:
  NODE_ENV: "test"

defaults:
 run:
  working-directory: ./frontend

jobs:
  build-test-app:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases/
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm ci
        npm run build
        npm run test
