apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 00000000000.dkr.ecr.ca-central-1.amazonaws.com/ai-flash-cards/frontend:latest # cherisecodes/ai-flash-cards-backend:latest
          env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: NODE_ENV
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
